apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scaletestapp-hpa
spec:
  maxReplicas: 10
  metrics:
    - pods:
        metric:
          name: http_requests_per_second
        target:
          type: AverageValue
          averageValue: "30"
      type: Pods
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scaletestapp-deployment
