http {
    # Ключ - значение заголовка Authorization (у каждого партнера свой уникальный API-ключ).
    # 10m - размер в памяти.
    # 10r/m - 10 запросов в минуту.
    limit_req_zone $http_authorization zone=api_limit:10m rate=10r/m;

    # Код ответа при превышении лимита
    limit_req_status 429;

    # Настройка upstream для балансировки нагрузки
    upstream backend_servers {
        server backend1.example.com;
        server backend2.example.com;
        server backend3.example.com;
    }

    server {
        listen 80;

        location / {
            # Включение rate limit.
            # nodelay - запросы, которые не прошли в лимит, сразу отклоняются.
            limit_req zone=api_limit nodelay;

            proxy_pass http://backend_servers;
        }
    }
}
